//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace _3DR_Testing.FedoraA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Fedora-API-A-Binding-SOAPHTTP", Namespace="http://www.fedora.info/definitions/1/0/api/")]
    public partial class FedoraAPIAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback describeRepositoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getObjectProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback listMethodsOperationCompleted;
        
        private System.Threading.SendOrPostCallback listDatastreamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDatastreamDisseminationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDisseminationOperationCompleted;
        
        private System.Threading.SendOrPostCallback findObjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback resumeFindObjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getObjectHistoryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FedoraAPIAService() {
            this.Url = global::_3DR_Testing.Properties.Settings.Default._3DR_Testing_FedoraA_Fedora_API_A_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event describeRepositoryCompletedEventHandler describeRepositoryCompleted;
        
        /// <remarks/>
        public event getObjectProfileCompletedEventHandler getObjectProfileCompleted;
        
        /// <remarks/>
        public event listMethodsCompletedEventHandler listMethodsCompleted;
        
        /// <remarks/>
        public event listDatastreamsCompletedEventHandler listDatastreamsCompleted;
        
        /// <remarks/>
        public event getDatastreamDisseminationCompletedEventHandler getDatastreamDisseminationCompleted;
        
        /// <remarks/>
        public event getDisseminationCompletedEventHandler getDisseminationCompleted;
        
        /// <remarks/>
        public event findObjectsCompletedEventHandler findObjectsCompleted;
        
        /// <remarks/>
        public event resumeFindObjectsCompletedEventHandler resumeFindObjectsCompleted;
        
        /// <remarks/>
        public event getObjectHistoryCompletedEventHandler getObjectHistoryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#describeRepository", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("repositoryInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RepositoryInfo describeRepository() {
            object[] results = this.Invoke("describeRepository", new object[0]);
            return ((RepositoryInfo)(results[0]));
        }
        
        /// <remarks/>
        public void describeRepositoryAsync() {
            this.describeRepositoryAsync(null);
        }
        
        /// <remarks/>
        public void describeRepositoryAsync(object userState) {
            if ((this.describeRepositoryOperationCompleted == null)) {
                this.describeRepositoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeRepositoryOperationCompleted);
            }
            this.InvokeAsync("describeRepository", new object[0], this.describeRepositoryOperationCompleted, userState);
        }
        
        private void OndescribeRepositoryOperationCompleted(object arg) {
            if ((this.describeRepositoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeRepositoryCompleted(this, new describeRepositoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#getObjectProfile", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objectProfile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ObjectProfile getObjectProfile([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string asOfDateTime) {
            object[] results = this.Invoke("getObjectProfile", new object[] {
                        pid,
                        asOfDateTime});
            return ((ObjectProfile)(results[0]));
        }
        
        /// <remarks/>
        public void getObjectProfileAsync(string pid, string asOfDateTime) {
            this.getObjectProfileAsync(pid, asOfDateTime, null);
        }
        
        /// <remarks/>
        public void getObjectProfileAsync(string pid, string asOfDateTime, object userState) {
            if ((this.getObjectProfileOperationCompleted == null)) {
                this.getObjectProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObjectProfileOperationCompleted);
            }
            this.InvokeAsync("getObjectProfile", new object[] {
                        pid,
                        asOfDateTime}, this.getObjectProfileOperationCompleted, userState);
        }
        
        private void OngetObjectProfileOperationCompleted(object arg) {
            if ((this.getObjectProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getObjectProfileCompleted(this, new getObjectProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#listMethods", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("objectMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ObjectMethodsDef[] listMethods([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string asOfDateTime) {
            object[] results = this.Invoke("listMethods", new object[] {
                        pid,
                        asOfDateTime});
            return ((ObjectMethodsDef[])(results[0]));
        }
        
        /// <remarks/>
        public void listMethodsAsync(string pid, string asOfDateTime) {
            this.listMethodsAsync(pid, asOfDateTime, null);
        }
        
        /// <remarks/>
        public void listMethodsAsync(string pid, string asOfDateTime, object userState) {
            if ((this.listMethodsOperationCompleted == null)) {
                this.listMethodsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistMethodsOperationCompleted);
            }
            this.InvokeAsync("listMethods", new object[] {
                        pid,
                        asOfDateTime}, this.listMethodsOperationCompleted, userState);
        }
        
        private void OnlistMethodsOperationCompleted(object arg) {
            if ((this.listMethodsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listMethodsCompleted(this, new listMethodsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#listDatastreams", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("datastreamDef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatastreamDef[] listDatastreams([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string asOfDateTime) {
            object[] results = this.Invoke("listDatastreams", new object[] {
                        pid,
                        asOfDateTime});
            return ((DatastreamDef[])(results[0]));
        }
        
        /// <remarks/>
        public void listDatastreamsAsync(string pid, string asOfDateTime) {
            this.listDatastreamsAsync(pid, asOfDateTime, null);
        }
        
        /// <remarks/>
        public void listDatastreamsAsync(string pid, string asOfDateTime, object userState) {
            if ((this.listDatastreamsOperationCompleted == null)) {
                this.listDatastreamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistDatastreamsOperationCompleted);
            }
            this.InvokeAsync("listDatastreams", new object[] {
                        pid,
                        asOfDateTime}, this.listDatastreamsOperationCompleted, userState);
        }
        
        private void OnlistDatastreamsOperationCompleted(object arg) {
            if ((this.listDatastreamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listDatastreamsCompleted(this, new listDatastreamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#getDatastreamDissemination", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("dissemination", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MIMETypedStream getDatastreamDissemination([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dsID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string asOfDateTime) {
            object[] results = this.Invoke("getDatastreamDissemination", new object[] {
                        pid,
                        dsID,
                        asOfDateTime});
            return ((MIMETypedStream)(results[0]));
        }
        
        /// <remarks/>
        public void getDatastreamDisseminationAsync(string pid, string dsID, string asOfDateTime) {
            this.getDatastreamDisseminationAsync(pid, dsID, asOfDateTime, null);
        }
        
        /// <remarks/>
        public void getDatastreamDisseminationAsync(string pid, string dsID, string asOfDateTime, object userState) {
            if ((this.getDatastreamDisseminationOperationCompleted == null)) {
                this.getDatastreamDisseminationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDatastreamDisseminationOperationCompleted);
            }
            this.InvokeAsync("getDatastreamDissemination", new object[] {
                        pid,
                        dsID,
                        asOfDateTime}, this.getDatastreamDisseminationOperationCompleted, userState);
        }
        
        private void OngetDatastreamDisseminationOperationCompleted(object arg) {
            if ((this.getDatastreamDisseminationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDatastreamDisseminationCompleted(this, new getDatastreamDisseminationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#getDissemination", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("dissemination", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MIMETypedStream getDissemination([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serviceDefinitionPid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string methodName, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("parameter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] Property[] parameters, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string asOfDateTime) {
            object[] results = this.Invoke("getDissemination", new object[] {
                        pid,
                        serviceDefinitionPid,
                        methodName,
                        parameters,
                        asOfDateTime});
            return ((MIMETypedStream)(results[0]));
        }
        
        /// <remarks/>
        public void getDisseminationAsync(string pid, string serviceDefinitionPid, string methodName, Property[] parameters, string asOfDateTime) {
            this.getDisseminationAsync(pid, serviceDefinitionPid, methodName, parameters, asOfDateTime, null);
        }
        
        /// <remarks/>
        public void getDisseminationAsync(string pid, string serviceDefinitionPid, string methodName, Property[] parameters, string asOfDateTime, object userState) {
            if ((this.getDisseminationOperationCompleted == null)) {
                this.getDisseminationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDisseminationOperationCompleted);
            }
            this.InvokeAsync("getDissemination", new object[] {
                        pid,
                        serviceDefinitionPid,
                        methodName,
                        parameters,
                        asOfDateTime}, this.getDisseminationOperationCompleted, userState);
        }
        
        private void OngetDisseminationOperationCompleted(object arg) {
            if ((this.getDisseminationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDisseminationCompleted(this, new getDisseminationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#findObjects", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FieldSearchResult findObjects([System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] string[] resultFields, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")] string maxResults, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] FieldSearchQuery query) {
            object[] results = this.Invoke("findObjects", new object[] {
                        resultFields,
                        maxResults,
                        query});
            return ((FieldSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void findObjectsAsync(string[] resultFields, string maxResults, FieldSearchQuery query) {
            this.findObjectsAsync(resultFields, maxResults, query, null);
        }
        
        /// <remarks/>
        public void findObjectsAsync(string[] resultFields, string maxResults, FieldSearchQuery query, object userState) {
            if ((this.findObjectsOperationCompleted == null)) {
                this.findObjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindObjectsOperationCompleted);
            }
            this.InvokeAsync("findObjects", new object[] {
                        resultFields,
                        maxResults,
                        query}, this.findObjectsOperationCompleted, userState);
        }
        
        private void OnfindObjectsOperationCompleted(object arg) {
            if ((this.findObjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findObjectsCompleted(this, new findObjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#resumeFindObjects", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FieldSearchResult resumeFindObjects([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sessionToken) {
            object[] results = this.Invoke("resumeFindObjects", new object[] {
                        sessionToken});
            return ((FieldSearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void resumeFindObjectsAsync(string sessionToken) {
            this.resumeFindObjectsAsync(sessionToken, null);
        }
        
        /// <remarks/>
        public void resumeFindObjectsAsync(string sessionToken, object userState) {
            if ((this.resumeFindObjectsOperationCompleted == null)) {
                this.resumeFindObjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresumeFindObjectsOperationCompleted);
            }
            this.InvokeAsync("resumeFindObjects", new object[] {
                        sessionToken}, this.resumeFindObjectsOperationCompleted, userState);
        }
        
        private void OnresumeFindObjectsOperationCompleted(object arg) {
            if ((this.resumeFindObjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resumeFindObjectsCompleted(this, new resumeFindObjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fedora.info/definitions/1/0/api/#getObjectHistory", RequestNamespace="http://www.fedora.info/definitions/1/0/types/", ResponseNamespace="http://www.fedora.info/definitions/1/0/types/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("modifiedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getObjectHistory([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pid) {
            object[] results = this.Invoke("getObjectHistory", new object[] {
                        pid});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getObjectHistoryAsync(string pid) {
            this.getObjectHistoryAsync(pid, null);
        }
        
        /// <remarks/>
        public void getObjectHistoryAsync(string pid, object userState) {
            if ((this.getObjectHistoryOperationCompleted == null)) {
                this.getObjectHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetObjectHistoryOperationCompleted);
            }
            this.InvokeAsync("getObjectHistory", new object[] {
                        pid}, this.getObjectHistoryOperationCompleted, userState);
        }
        
        private void OngetObjectHistoryOperationCompleted(object arg) {
            if ((this.getObjectHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getObjectHistoryCompleted(this, new getObjectHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class RepositoryInfo {
        
        private string repositoryNameField;
        
        private string repositoryVersionField;
        
        private string repositoryBaseURLField;
        
        private string repositoryPIDNamespaceField;
        
        private string defaultExportFormatField;
        
        private string oAINamespaceField;
        
        private string[] adminEmailListField;
        
        private string samplePIDField;
        
        private string sampleOAIIdentifierField;
        
        private string sampleSearchURLField;
        
        private string sampleAccessURLField;
        
        private string sampleOAIURLField;
        
        private string[] retainPIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string repositoryName {
            get {
                return this.repositoryNameField;
            }
            set {
                this.repositoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string repositoryVersion {
            get {
                return this.repositoryVersionField;
            }
            set {
                this.repositoryVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string repositoryBaseURL {
            get {
                return this.repositoryBaseURLField;
            }
            set {
                this.repositoryBaseURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string repositoryPIDNamespace {
            get {
                return this.repositoryPIDNamespaceField;
            }
            set {
                this.repositoryPIDNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string defaultExportFormat {
            get {
                return this.defaultExportFormatField;
            }
            set {
                this.defaultExportFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string OAINamespace {
            get {
                return this.oAINamespaceField;
            }
            set {
                this.oAINamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] adminEmailList {
            get {
                return this.adminEmailListField;
            }
            set {
                this.adminEmailListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string samplePID {
            get {
                return this.samplePIDField;
            }
            set {
                this.samplePIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sampleOAIIdentifier {
            get {
                return this.sampleOAIIdentifierField;
            }
            set {
                this.sampleOAIIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sampleSearchURL {
            get {
                return this.sampleSearchURLField;
            }
            set {
                this.sampleSearchURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sampleAccessURL {
            get {
                return this.sampleAccessURLField;
            }
            set {
                this.sampleAccessURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sampleOAIURL {
            get {
                return this.sampleOAIURLField;
            }
            set {
                this.sampleOAIURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] retainPIDs {
            get {
                return this.retainPIDsField;
            }
            set {
                this.retainPIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class ObjectFields {
        
        private string pidField;
        
        private string labelField;
        
        private string stateField;
        
        private string ownerIdField;
        
        private string cDateField;
        
        private string mDateField;
        
        private string dcmDateField;
        
        private string[] titleField;
        
        private string[] creatorField;
        
        private string[] subjectField;
        
        private string[] descriptionField;
        
        private string[] publisherField;
        
        private string[] contributorField;
        
        private string[] dateField;
        
        private string[] typeField;
        
        private string[] formatField;
        
        private string[] identifierField;
        
        private string[] sourceField;
        
        private string[] languageField;
        
        private string[] relationField;
        
        private string[] coverageField;
        
        private string[] rightsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ownerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cDate {
            get {
                return this.cDateField;
            }
            set {
                this.cDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mDate {
            get {
                return this.mDateField;
            }
            set {
                this.mDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string dcmDate {
            get {
                return this.dcmDateField;
            }
            set {
                this.dcmDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creator", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subject", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisher", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contributor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] contributor {
            get {
                return this.contributorField;
            }
            set {
                this.contributorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("date", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("format", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("language", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("coverage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] coverage {
            get {
                return this.coverageField;
            }
            set {
                this.coverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rights", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] rights {
            get {
                return this.rightsField;
            }
            set {
                this.rightsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class ListSession {
        
        private string tokenField;
        
        private string cursorField;
        
        private string completeListSizeField;
        
        private string expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
        public string cursor {
            get {
                return this.cursorField;
            }
            set {
                this.cursorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="nonNegativeInteger")]
        public string completeListSize {
            get {
                return this.completeListSizeField;
            }
            set {
                this.completeListSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class FieldSearchResult {
        
        private ListSession listSessionField;
        
        private ObjectFields[] resultListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ListSession listSession {
            get {
                return this.listSessionField;
            }
            set {
                this.listSessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objectFields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ObjectFields[] resultList {
            get {
                return this.resultListField;
            }
            set {
                this.resultListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class Condition {
        
        private string propertyField;
        
        private System.Nullable<ComparisonOperator> operatorField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string property {
            get {
                return this.propertyField;
            }
            set {
                this.propertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<ComparisonOperator> @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum ComparisonOperator {
        
        /// <remarks/>
        has,
        
        /// <remarks/>
        eq,
        
        /// <remarks/>
        lt,
        
        /// <remarks/>
        le,
        
        /// <remarks/>
        gt,
        
        /// <remarks/>
        ge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class FieldSearchQuery {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conditions", typeof(FieldSearchQueryConditions), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlElementAttribute("terms", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class FieldSearchQueryConditions {
        
        private Condition[] conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("condition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Condition[] condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class Property {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class MIMETypedStream {
        
        private string mIMETypeField;
        
        private byte[] streamField;
        
        private Property[] headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string MIMEType {
            get {
                return this.mIMETypeField;
            }
            set {
                this.mIMETypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] stream {
            get {
                return this.streamField;
            }
            set {
                this.streamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class DatastreamDef {
        
        private string idField;
        
        private string labelField;
        
        private string mIMETypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string MIMEType {
            get {
                return this.mIMETypeField;
            }
            set {
                this.mIMETypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class MethodParmDef {
        
        private string parmNameField;
        
        private string parmTypeField;
        
        private string parmDefaultValueField;
        
        private string[] parmDomainValuesField;
        
        private bool parmRequiredField;
        
        private string parmLabelField;
        
        private string parmPassByField;
        
        private System.Nullable<passByRef> pASS_BY_REFField;
        
        private System.Nullable<passByValue> pASS_BY_VALUEField;
        
        private System.Nullable<datastreamInputType> dATASTREAM_INPUTField;
        
        private System.Nullable<userInputType> uSER_INPUTField;
        
        private System.Nullable<defaultInputType> dEFAULT_INPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string parmName {
            get {
                return this.parmNameField;
            }
            set {
                this.parmNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string parmType {
            get {
                return this.parmTypeField;
            }
            set {
                this.parmTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string parmDefaultValue {
            get {
                return this.parmDefaultValueField;
            }
            set {
                this.parmDefaultValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] parmDomainValues {
            get {
                return this.parmDomainValuesField;
            }
            set {
                this.parmDomainValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool parmRequired {
            get {
                return this.parmRequiredField;
            }
            set {
                this.parmRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string parmLabel {
            get {
                return this.parmLabelField;
            }
            set {
                this.parmLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string parmPassBy {
            get {
                return this.parmPassByField;
            }
            set {
                this.parmPassByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<passByRef> PASS_BY_REF {
            get {
                return this.pASS_BY_REFField;
            }
            set {
                this.pASS_BY_REFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<passByValue> PASS_BY_VALUE {
            get {
                return this.pASS_BY_VALUEField;
            }
            set {
                this.pASS_BY_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<datastreamInputType> DATASTREAM_INPUT {
            get {
                return this.dATASTREAM_INPUTField;
            }
            set {
                this.dATASTREAM_INPUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<userInputType> USER_INPUT {
            get {
                return this.uSER_INPUTField;
            }
            set {
                this.uSER_INPUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<defaultInputType> DEFAULT_INPUT {
            get {
                return this.dEFAULT_INPUTField;
            }
            set {
                this.dEFAULT_INPUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum passByRef {
        
        /// <remarks/>
        URL_REF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum passByValue {
        
        /// <remarks/>
        VALUE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum datastreamInputType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("fedora:datastreamInputType")]
        fedoradatastreamInputType,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum userInputType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("fedora:userInputType")]
        fedorauserInputType,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public enum defaultInputType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("fedora:defaultInputType")]
        fedoradefaultInputType,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class ObjectMethodsDef {
        
        private string pIDField;
        
        private string serviceDefinitionPIDField;
        
        private string methodNameField;
        
        private MethodParmDef[] methodParmDefsField;
        
        private string asOfDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceDefinitionPID {
            get {
                return this.serviceDefinitionPIDField;
            }
            set {
                this.serviceDefinitionPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("methodParmDef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public MethodParmDef[] methodParmDefs {
            get {
                return this.methodParmDefsField;
            }
            set {
                this.methodParmDefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string asOfDate {
            get {
                return this.asOfDateField;
            }
            set {
                this.asOfDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fedora.info/definitions/1/0/types/")]
    public partial class ObjectProfile {
        
        private string pidField;
        
        private string objLabelField;
        
        private string[] objModelsField;
        
        private string objCreateDateField;
        
        private string objLastModDateField;
        
        private string objDissIndexViewURLField;
        
        private string objItemIndexViewURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objLabel {
            get {
                return this.objLabelField;
            }
            set {
                this.objLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("model", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] objModels {
            get {
                return this.objModelsField;
            }
            set {
                this.objModelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objCreateDate {
            get {
                return this.objCreateDateField;
            }
            set {
                this.objCreateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objLastModDate {
            get {
                return this.objLastModDateField;
            }
            set {
                this.objLastModDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objDissIndexViewURL {
            get {
                return this.objDissIndexViewURLField;
            }
            set {
                this.objDissIndexViewURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string objItemIndexViewURL {
            get {
                return this.objItemIndexViewURLField;
            }
            set {
                this.objItemIndexViewURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void describeRepositoryCompletedEventHandler(object sender, describeRepositoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeRepositoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeRepositoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RepositoryInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RepositoryInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getObjectProfileCompletedEventHandler(object sender, getObjectProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getObjectProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getObjectProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectProfile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectProfile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void listMethodsCompletedEventHandler(object sender, listMethodsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listMethodsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listMethodsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ObjectMethodsDef[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ObjectMethodsDef[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void listDatastreamsCompletedEventHandler(object sender, listDatastreamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listDatastreamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listDatastreamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatastreamDef[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatastreamDef[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getDatastreamDisseminationCompletedEventHandler(object sender, getDatastreamDisseminationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDatastreamDisseminationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDatastreamDisseminationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MIMETypedStream Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MIMETypedStream)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getDisseminationCompletedEventHandler(object sender, getDisseminationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDisseminationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDisseminationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MIMETypedStream Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MIMETypedStream)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void findObjectsCompletedEventHandler(object sender, findObjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void resumeFindObjectsCompletedEventHandler(object sender, resumeFindObjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resumeFindObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resumeFindObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FieldSearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FieldSearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getObjectHistoryCompletedEventHandler(object sender, getObjectHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getObjectHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getObjectHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591